version: '3.4'

services:
  app:
    build:
      context: .
      target: "${EDX2GIFT_IMAGE_BUILD_TARGET:-development}"
      args:
        DOCKER_USER: ${DOCKER_USER:-1000}
    user: ${DOCKER_USER:-1000}
    image: "${EDX2GIFT_IMAGE_NAME:-edx2gift}:${EDX2GIFT_IMAGE_TAG:-development}"
    env_file:
      - .env
    environment:
      PYLINTHOME: /app/.pylint.d
    ports:
      - "${EDX2GIFT_SERVER_PORT:-8100}:${EDX2GIFT_SERVER_PORT:-8100}"
    command:
      - uvicorn
      - "edx2gift.api:app"
      - "--proxy-headers"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "${EDX2GIFT_SERVER_PORT:-8100}"
      - "--reload"
    volumes:
      - .:/app
